# Generated by Django 5.2 on 2025-07-08 02:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PreguntasFrecuentes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255, verbose_name="Título")),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("USO", "Uso de la app"),
                            ("CUENTA", "Cuenta"),
                            ("TECNICO", "Soporte técnico"),
                            ("GENERAL", "General"),
                        ],
                        max_length=20,
                        verbose_name="Categorías",
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0, verbose_name="Orden")),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualizacón"
                    ),
                ),
            ],
            options={
                "ordering": ["orden", "-fecha_creacion"],
            },
        ),
    ]
