# Generated by Django 5.2 on 2025-07-09 18:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("preguntas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="preguntasfrecuentes",
            name="contenido",
            field=ckeditor.fields.RichTextField(
                default="contenido pendiente", verbose_name="contenido"
            ),
        ),
    ]
