# Generated by Django 5.2 on 2025-07-13 04:32

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("contenido", ckeditor_uploader.fields.RichTextUploadingField()),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="imagen_post"),
                ),
                ("publicado", models.BooleanField(default=False)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                ("url_info", models.URLField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
                "ordering": ["-creado"],
            },
        ),
    ]
