# Generated by Django 5.2 on 2025-07-13 05:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="contenido",
            field=models.TextField(),
        ),
    ]
