# Generated by Django 5.2 on 2025-07-13 05:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Blog", "0002_alter_post_contenido"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="contenido",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
