# Generated by Django 5.2 on 2025-07-03 23:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacto", "0003_alter_informacioncontacto_hora_apertura_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="informacioncontacto",
            options={
                "verbose_name": "Información de contacto",
                "verbose_name_plural": "Información de contacto",
            },
        ),
        migrations.AddField(
            model_name="informacioncontacto",
            name="hora_apertura_sabado",
            field=models.IntegerField(
                choices=[
                    (0, "0:00"),
                    (1, "1:00"),
                    (2, "2:00"),
                    (3, "3:00"),
                    (4, "4:00"),
                    (5, "5:00"),
                    (6, "6:00"),
                    (7, "7:00"),
                    (8, "8:00"),
                    (9, "9:00"),
                    (10, "10:00"),
                    (11, "11:00"),
                    (12, "12:00"),
                    (13, "13:00"),
                    (14, "14:00"),
                    (15, "15:00"),
                    (16, "16:00"),
                    (17, "17:00"),
                    (18, "18:00"),
                    (19, "19:00"),
                    (20, "20:00"),
                    (21, "21:00"),
                    (22, "22:00"),
                    (23, "23:00"),
                ],
                default=10,
                verbose_name="Horario apertura",
            ),
        ),
        migrations.AddField(
            model_name="informacioncontacto",
            name="hora_cierre_sabado",
            field=models.IntegerField(
                choices=[
                    (0, "0:00"),
                    (1, "1:00"),
                    (2, "2:00"),
                    (3, "3:00"),
                    (4, "4:00"),
                    (5, "5:00"),
                    (6, "6:00"),
                    (7, "7:00"),
                    (8, "8:00"),
                    (9, "9:00"),
                    (10, "10:00"),
                    (11, "11:00"),
                    (12, "12:00"),
                    (13, "13:00"),
                    (14, "14:00"),
                    (15, "15:00"),
                    (16, "16:00"),
                    (17, "17:00"),
                    (18, "18:00"),
                    (19, "19:00"),
                    (20, "20:00"),
                    (21, "21:00"),
                    (22, "22:00"),
                    (23, "23:00"),
                ],
                default=2,
                verbose_name="Hora de cierre",
            ),
        ),
    ]
