# Generated by Django 5.2 on 2025-06-17 20:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gastos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="presupuesto",
            options={
                "ordering": ["-fecha_de_expiracion"],
                "verbose_name": "Presupuesto",
                "verbose_name_plural": "Presupuestos",
            },
        ),
        migrations.AddField(
            model_name="categoria",
            name="usuario",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="gasto",
            name="archivo_adjunto",
            field=models.FileField(blank=True, null=True, upload_to="gastos_archivos/"),
        ),
        migrations.AddField(
            model_name="gasto",
            name="metodo_pago",
            field=models.CharField(
                choices=[
                    ("efectivo", "Efectivo"),
                    ("tarjeta_debito", "Tarjeta de Débito"),
                    ("tarjeta_credito", "Tarjeta de Crédito"),
                    ("transferencia", "Transferencia Bancaria"),
                    ("mercado_pago", "Mercado Pago"),
                    ("otro", "Otro"),
                ],
                default="efectivo",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="gasto",
            name="nota_adicionales",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="presupuesto",
            name="fecha_modificacion",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
