# Generated by Django 5.2 on 2025-06-17 20:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gastos", "0002_alter_presupuesto_options_categoria_usuario_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="presupuesto",
            name="fecha_modificacion",
        ),
    ]
