# Generated by Django 5.2 on 2025-06-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gastos", "0003_remove_presupuesto_fecha_modificacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="presupuesto",
            name="fecha_actualizacion",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
