# Generated by Django 5.2 on 2025-06-18 02:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gastos", "0004_presupuesto_fecha_actualizacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="gasto",
            name="fehca_modificacion",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="gasto",
            name="metodo_pago",
            field=models.CharField(
                choices=[
                    ("efectivo", "💵 Efectivo"),
                    ("tarjeta_debito", "💳 Tarjeta de Débito"),
                    ("tarjeta_credito", "💳 Tarjeta de Crédito"),
                    ("transferencia", "🏦 Transferencia Bancaria"),
                    ("mercado_pago", "📱 Mercado Pago"),
                    ("otro", "🧾 Otro"),
                ],
                default="efectivo",
                max_length=30,
            ),
        ),
    ]
