# Generated by Django 5.2 on 2025-06-18 02:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gastos", "0005_gasto_fehca_modificacion_alter_gasto_metodo_pago"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gasto",
            old_name="fehca_modificacion",
            new_name="fecha_modificacion",
        ),
    ]
