# Generated by Django 5.2 on 2025-07-04 01:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        max_length=100, unique=True, verbose_name="nombre clave"
                    ),
                ),
                ("nombre", models.CharField(verbose_name="red social")),
                (
                    "url",
                    models.DateTimeField(
                        blank=True, max_length=200, null=True, verbose_name="Enlace"
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creacion"
                    ),
                ),
                (
                    "actualizado",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de edición"
                    ),
                ),
            ],
            options={
                "verbose_name": "Enlace",
                "verbose_name_plural": "Enlaces",
                "ordering": ["nombre"],
            },
        ),
    ]
